## Förbättra mixandMatch description
* [#33](https://github.com/salgo60/ifkdb/issues/33)
* Denna notebook [33_difhistoryplayer](https://github.com/salgo60/ifkdb/blob/main/Notebook/33_difhistoryplayer.ipynb)

In [1]:
from datetime import datetime
import platform
import sys
import os

# Start timer
start_time = datetime.now()
print(f"Start time: {start_time:%Y-%m-%d %H:%M:%S}")

Start time: 2026-03-05 23:58:08

In [2]:
filename="difplayers.json"

In [3]:
import json
from pprint import pprint

# Read JSON
with open(filename, "r", encoding="utf-8") as f:
    data = json.load(f)

# Show top-level structure
print("Top level type:", type(data))

# Count items
if isinstance(data, list):
    print("Number of items:", len(data))
elif isinstance(data, dict):
    print("Number of keys:", len(data))
else:
    print("Unknown JSON structure")

# Show structure sample
print("\nSample structure:")
if isinstance(data, list) and len(data) > 0:
    pprint(data[0])
elif isinstance(data, dict):
    pprint(list(data.keys()))

Top level type: <class 'list'>
Number of items: 1105

Sample structure:
{'auxiliary_data': None,
 'born': None,
 'catalog': '7278',
 'dates_in_wikidata': None,
 'description': '',
 'died': None,
 'entry_id': '225596324',
 'entry_type': 'Q5',
 'external_id': 'marja-aaltonen',
 'external_url': 'https://difhistoria.se/marja-aaltonen',
 'lat': None,
 'lon': None,
 'matched_by_username': 'Sabelöga',
 'matched_on': '20251217144436',
 'mnm_user_id': '6575119',
 'multi_match_candidates': None,
 'name': 'Marja Aaltonen',
 'q': 'Q24827502'}

In [4]:
import json
import pandas as pd

# Load JSON
with open(filename, "r", encoding="utf-8") as f:
    data = json.load(f)

# Create dataframe
df = pd.DataFrame(data)

# Count values in description field
desc_counts = df["description"].value_counts(dropna=False)

print(desc_counts)

description
    1105
Name: count, dtype: int64

In [5]:
import json
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

df = pd.DataFrame(data)

headers = {
    "User-Agent": "Mozilla/5.0"
}

def scrape_infobox(url):
    try:
        r = requests.get(url, headers=headers, timeout=20)
        soup = BeautifulSoup(r.text, "html.parser")

        section = soup.find("section", class_="wp-block-uagb-section")

        if not section:
            return None

        text = section.get_text(separator=" ", strip=True)
        return text

    except Exception as e:
        print("Error:", url, e)
        return None


# Loop through rows
results = []

for url in df["external_url"]:
    print("Scraping:", url)
    info = scrape_infobox(url)
    print ("\t",info)
    results.append(info)

    #time.sleep(1)  # be polite

df["infobox"] = results

Scraping: https://difhistoria.se/marja-aaltonen
	 Marja Aaltonen Född: 13 maj 1964 Fotbollsspelare Position: målvakt Nummer: 1 Moderklubb: FC Honka (Finland) 1989 1991
Scraping: https://difhistoria.se/alexander-abrahamsson
	 Nils Oscar Alexander Abrahamsson Född: 7 augusti 1999 Fotbollsspelare Position: back Nummer: 28 Moderklubb: Sunnesta IF 5 säsonger. 2015 2016 2017 2018 2019
Scraping: https://difhistoria.se/albion-ademi
	 Albion Ademi Född: 19 februari 1999 Fotbollsspelare Position: mittfältare Längd: 173 cm Nummer: 11 Moderklubb: TPS (Finland) 2021 2022 2023
Scraping: https://difhistoria.se/gale-agbossoumonde
	 Gale Agbossoumonde Född: 17 november 1991 Fotbollsspelare Position: försvarare Moderklubb: Miami F.C. (USA) 1 säsong. 14 matcher. 0 mål. 2011 8 0
Scraping: https://difhistoria.se/bengt-agfemalm
	 Bengt Frans Agfemalm Född: 24 augusti 1930 Curlingspelare Moderklubb: ? x säsonger. 19xx 19xx
Scraping: https://difhistoria.se/nicolaj-agger
	 Nicolaj Moesgaard Agger Född: 23 oktober 1988 Fotbollsspelare Position: anfallare Moderklubb: Brøndby IF (Danmark). 1 säsong. 7 matcher. 1 mål. 2011 7 1
Scraping: https://difhistoria.se/christer-ahlstrand
	 Christer Ahlstrand Född: 16 juli 1949 Ishockeyspelare Position: back Moderklubb: Tranås AIF Säsonger Matcher Mål Assist Poäng 1969/70 13 1 1 2 1970/71 1 0 0 0
Scraping: https://difhistoria.se/anders-ahlstrom
	 Sven Anders Ahlström Född: 1 augusti 1948 Fotbollsspelare Position: center Moderklubb: Brynäs IF 2 säsonger. 27 matcher. 10 mål. 1972 18 10 1973 9 0
Scraping: https://difhistoria.se/erik-ahlstrom
	 Bo Erik Ahlström Född: 27 februari 1964 Ishockeyspelare Position: forward Moderklubb: Djurgårdens IF Säsonger Matcher Mål Assist Poäng 1983/84 3 0 0 0 1984/85 14 2 4 6 1985/86 26 2 4 6
Scraping: https://difhistoria.se/astrit-ajdarevic
	 Astrit Ajdarevic Född: 17 april 1990 Fotbollsspelare Position: mittfältare Nummer: 10 Moderklubb: Falkenbergs FF 1 säsong. 26 matcher. 0 mål. 2019 26 0
Scraping: https://difhistoria.se/tommy-albelin
	 Tommy Albelin Född: 21 maj 1964 Ishockeyspelare Position: back Moderklubb: IF Brommapojkarna Säsonger Matcher Mål Assist Poäng 1982/83 19 2 5 7 1983/84 30 9 4 13 1984/85 32 8 8 16 1985/86 35 4 8 12 1986/87 33 7 5 12
Scraping: https://difhistoria.se/bengt-albertz
	 Bengt Albertz Född: Fotbollsspelare Position: Moderklubb: 3 säsonger. 1 mål. 1937/38 – 1 1938/39 – 0 1939/40 – 0
Scraping: https://difhistoria.se/maria-alcander
	 Maria Alcander Född: Fotbollsspelare Position: Nummer: 8 Moderklubb: 1988
Scraping: https://difhistoria.se/isak-alemayehu
	 Isak Alexander Alemayehu Född: 11 oktober 2006 Fotbollsspelare Position: mittfältare Längd: 177 cm Nummer: 20 Moderklubb: Djurgårdens IF 2 säsonger. 1 matcher. 0 mål. 2022 1 0 2023
Scraping: https://difhistoria.se/gissle-alfredsson
	 Gissle Alfredsson Född: 27 maj 1941 Bandyspelare 2 säsonger. 1965 1966
Scraping: https://difhistoria.se/bjorn-alkeby
	 Lennart Björn Alkeby Född: 17 juli 1952 Fotbollsspelare Position: målvakt. Moderklubb: Danderyds SK 13 säsonger. 243 matcher. 0 mål. 1971 16 0 1972 22 0 1973 26 0 1974 26 0 1975 25 0 1976 26 0 1977 26 0 1978 15 0 1979 16 0 1980 26 0 1981 18 0 1982 24 0 1993 1 0
Scraping: https://difhistoria.se/malin-allberg
	 Malin Eva Helena Allberg Född: 1 mars 1972 Fotbollsspelare Position: mittfältare Nummer: 14 Moderklubb: Vällingby AIK 1990 1991 1992
Scraping: https://difhistoria.se/ruben-allinger
	 Karl Ruben Allinger Född: 23 december 1891 Ishockeyspelare Position: back Moderklubb: ? Säsonger Matcher Mål Assist Poäng 1921/22 – – – – 1922/23 – – – – 1923/24 – – – – 1924/25 – – – – 1925/26 – – – – 1926/27 – – – – 1927/28 – – – – 1928/29 – – – – 1929/30 – – – – 1930/31 – – – –
Scraping: https://difhistoria.se/johan-alm
	 Johan Krister Alm Född: 28 januari 1992 Ishockeyspelare Position: back Längd: 190 cm Nummer: 7 Skjuter: vänster Moderklubb: Skellefteå AIK Säsonger Matcher Mål Assist Poäng 2022/23 21 1 3 4
Scraping: https://difhistoria.se/anders-almgren
	 Jan Anders Fredrik Almgren Född: 27 december 1968 Fotbollsspelare Position: målvakt Moderklubb: Djurö-Vindö IF 5 säsonger. 70 matcher. 0 mål. 1988 4 0 1989 22 0 1990 19 0 1991 19 0 1992 6 0
Scraping: https://difhistoria.se/joakim-alriksson
	 Axel Joakim Alriksson Född: 18 augusti 1992 Fotbollsspelare Position: mittfältare Moderklubb: Heby AIF 2 säsonger. 5 matcher. 0 mål. 2010 1 0 2011 4 0
Scraping: https://difhistoria.se/stefan-alven
	 Björn Stefan Alvén Född: 12 december 1968 Fotbollsspelare Position: försvarare. Moderklubb: Asmundstorp IF 5 säsonger. 122 matcher. 2 mål. 1995 24 0 1996 25 1 1997 24 1 1998 25 0 1999 24 0
Scraping: https://difhistoria.se/daniel-amartey
	 Daniel Amartey Född: 21 december 1994 Fotbollsspelare Position: mittfältare/försvarare Moderklubb: Inter Allies (Ghana) 2 säsonger. 34 matcher. 0 mål. 2013 23 0 2014 11 0
Scraping: https://difhistoria.se/patrick-amoah
	 Patrick James Amoah Född: 18 augusti 1986 Fotbollsspelare Position: anfallare Moderklubb: Djurgårdens IF 3 säsonger. 40 matcher. 4 mål 2004 10 2 2005 17 1 2006 ? 2007 13 1
Scraping: https://difhistoria.se/bo-braastrup-andersen
	 Bo Braastrup Andersen Född: 26 mars 1976 Fotbollsspelare Position: målvakt Moderklubb: Lyngby FC 1 säsong. 11 matcher. 0 mål. 1999 11 0
Scraping: https://difhistoria.se/arne-andersen
	 Arne Ingvar Andersén Född: 4 maj 1956 Ishockeyspelare Position: back Moderklubb: Kiruna AIF Säsonger Matcher Mål Assist Poäng 1977/78 16 2 2 4 1978/79 3 3 0 0
Scraping: https://difhistoria.se/anders-andersson-bernmar
	 Anders Andersson (f.d. Bernmar) Född: 30 september 1917 Fotbollsspelare Position: försvarare Moderklubb: Helsingborgs IF 4 säsonger. 2 mål. 1939/40 – 1 1940/41 – 0 1941/42 – 1 1942/43 – 0
Scraping: https://difhistoria.se/bernt-hugo-andersson
	 Bernt Hugo Erland Andersson Född: 5 september 1933 Fotbollsspelare Position: ytter Moderklubb: Sundbybergs IK 9 säsonger. 89 matcher. 19 mål. 1952/53 6 0 1953/54 16 4 1954/55 18 4 SM-guld. 1955/56 2 0 1956/57 6 2 1957/58 8 3 1960 9 0 1964 9 3 SM-guld. 1965 15 3
Scraping: https://difhistoria.se/bertil-andersson
	 Ragnar Vilhelm Bertil Andersson Född: 7 mars 1905 Fotbollsspelare Position: försvarare Moderklubb: Djurgårdens IF 6 säsonger. 59 matcher. 4 mål. 1927/28 3 0 1928 ? 1929 ? 1930 ? 1931 ? 1932/33 11 0 1933/34 – 0 1934/35 16 4 1935/36 18 0 1936/37 11 0
Scraping: https://difhistoria.se/bertil-jeppe-andersson
	 Nils Bertil Andersson (senare Aldrin) Född: 4 september 1905 Fotbollsspelare Position: Moderklubb: 1 säsong. 7 matcher. 8 mål. 1927/28 7 8
Scraping: https://difhistoria.se/bo-superbosse-andersson
	 Bo Magnus Andersson Född: 26 augusti 1968 Fotbollsspelare Position: anfallare Moderklubb: Vasalunds IF 4 säsonger. 87 matcher. 41 mål. 1994 25 11 1995 23 11 1996 19 4 1997 20 2
Scraping: https://difhistoria.se/bror-andersson
	 Bror Oskar Andersson Född: 11 februari 1925 Ishockeyspelare Position: back Moderklubb: Tranebergs IF Säsonger Matcher Mål Assist Poäng 1948/49 4 0 0 0
Scraping: https://difhistoria.se/borje-andersson
	 Stig Börje Andersson Född: 30 mars 1946 Ishockeyspelare Position: forward Moderklubb: Djurgårdens IF Säsonger Matcher Mål Assist Poäng 1965/66 10 3 3 6
Scraping: https://difhistoria.se/carl-potis-andersson
	 Carl Mauritz Andersson Född: 22 september 1900 Fotbollsspelare Position: försvarare Moderklubb: Tranebergs IF 1 säsong. 18 matcher. 0 mål. 1927/28 18 0
Scraping: https://difhistoria.se/christer-andersson
	 Christer Andersson Född: 1940 Fotbollsspelare Position: anfallare Moderklubb: Djurgårdens IF 1 säsong. 3 matcher. 3 mål. 1961 3 3
Scraping: https://difhistoria.se/elias-andersson
	 Nils Erik Elias Andersson Född: 31 januari 1996 Fotbollsspelare Position: mittfältare Längd: 178 cm Nummer: 8 Moderklubb: Hässleholms IF 2021 2022 2023
Scraping: https://difhistoria.se/gustaf-andersson
	 Gustaf Adolf Andersson Född: 2 januari 1868 Medlem: 15 Grundare av Djurgårdens IF
Scraping: https://difhistoria.se/hans-andersson
	 Hans Gunnar Andersson Född: 7 februari 1945 Fotbollsspelare Position: ytter Moderklubb: 1 säsong. 4 matcher. 0 mål. 1965 4 0
Scraping: https://difhistoria.se/harry-andersson
	 Harry Arvid Verner Andersson Född: 20 mars 1912 Fotbollsspelare Position: försvarare Moderklubb: Sandvikens IF 5 säsonger. 28 matcher. 3 mål. 1932/33 – 0 1933/34 16 1 1934/35 11 2 1935/36 – 0 1936/37 1 0 Handbollsspelare 1937 1938 1939 1940 1941
Scraping: https://difhistoria.se/ivar-packarn-andersson
	 Karl Ivar Andersson Född: 10 januari 1903 Fotbollsspelare Position: Moderklubb: 1 säsong. 17 matcher. 0 mål. 1927/28 17 0
Scraping: https://difhistoria.se/jan-andersson
	 Jan Edgar Andersson Född: 7 maj 1965 Fotbollsspelare Position: försvarare Moderklubb: IFK Västerås 3 säsonger. 38 matcher. 4 mål. 1990 12 0 1991 15 3 1992 11 1
Scraping: https://difhistoria.se/johan-andersson-2
	 Carl Johan Josef Andersson Född: 15 juni 1995 Fotbollsspelare Position: försvarare Nummer: 2 Moderklubb: Vaksala SK 2 säsonger. 2 matcher. 0 mål. 2018 1 0 2019 1 0
Scraping: https://difhistoria.se/john-andersson
	 John Harry Alexander Andersson Född: 2 mars 1909 Boxare Europamästare 1933 SM-guld 1929, 1931
Scraping: https://difhistoria.se/karl-erik-cacka-andersson
	 Karl-Erik Andersson Född: 16 januari 1927 SM-guld: 1954/55 (fotboll), 1950, 1954, 1955 (ishockey) Fotbollsspelare Position: försvarare Moderklubb: Djurgårdens IF 13 säsonger. 141 matcher. 3 mål. 1945/46 6 0 1946/47 22 0 1947/48 21 0 1948/49 – 0 1949/50 22 0 1950/51 6 0 1951/52 16 0 1952/53 22 0 1953/54 19 1 1954/55 22 2 1955/56 13 0 1956/57 7 0 1957/58 6 0 Ishockeyspelare Position: forward Moderklubb: Djurgårdens IF Säsonger Matcher Mål Assist Poäng 1947/48 – – – – 1948/49 – – – – 1949/50 – – – – 1950/51 – – – – 1951/52 – – – – 1952/53 – – – – 1953/54 – – – –
Scraping: https://difhistoria.se/karl-olof-andersson
	 Karl-Olof Andersson Född: 12 juni 1942 Fotbollsspelare Position: anfallare Moderklubb: IK Tord 1 säsong. 4 matcher. 0 1965 4 0
Scraping: https://difhistoria.se/lars-andersson
	 Karl Lars Andersson (senare Widerström) Född: 30 januari 1927 Fotbollsspelare Position: högerinner Moderklubb: Gais 1 säsong. 2 matcher. 0 mål. 1950/51 2 0
Scraping: https://difhistoria.se/martin-andersson
	 Erik Martin Andersson Född: 9 maj 1982 Fotbollsspelare Position: mittback/mittfältare Moderklubb: Enköpings SK 2 säsonger. 16 matcher. 0 mål. 2008 13 0 2009 3 0
Scraping: https://difhistoria.se/n-andersson
	 N. Andersson Född: Fotbollsspelare Position: Moderklubb: 1 säsong. 0 mål. 1939/40 – 0
Scraping: https://difhistoria.se/nils-andersson
	 Nils Åke Andersson Född: 28 augusti 1941 Fotbollsspelare Position: försvarare Moderklubb: Spånga IS 2 säsonger. 11 matcher. 0 mål. 1960 9 0 1961 2 0 Bandyspelare Position: målvakt 2 säsonger. 1962 1963
Scraping: https://difhistoria.se/per-ake-andersson
	 Per-Åke Andersson Född: 4 juni 1939 Bandyspelare 2 säsonger. 1965 1966
Scraping: https://difhistoria.se/rickard-parris-andersson
	 Rickard Ferdinand Andersson Född: 22 juni 1897 Fotbollsspelare Position: målvakt Moderklubb: ? 1 säsong. 13 matcher. 0 mål. 1927/1928 13 0
Scraping: https://difhistoria.se/roland-andersson
	 Åke Erik Roland Andersson Född: 28 mars 1950 Fotbollsspelare Position: högerback Moderklubb: Malmö FF 2 säsonger. 45 matcher. 2 mål. 1975 23 2 1976 22 0
Scraping: https://difhistoria.se/rose-marie-andersson
	 Rose-Marie Linda Andersson Född: 22 mars 1973 Fotbollsspelare Position: back, mittfältare Nummer: 21, 11 Moderklubb: IFK Österåker 1989 1990 1991 1992 1996
Scraping: https://difhistoria.se/rune-andersson
	 Rune Andersson Född: Fotbollsspelare Position: Moderklubb: 1 säsong. 4 matcher. 0 mål. 1944/45 4 0
Scraping: https://difhistoria.se/sebastian-andersson
	 Martin Sebastian Andersson Född: 15 juli 1991 Fotbollsspelare Position: anfallare Moderklubb: Vinslövs IF 2 säsonger. 35 matcher. 13 mål. 2014 13 6 2015 22 7
Scraping: https://difhistoria.se/sven-andersson
	 Sven Andersson Född: 6 november 1932 Ishockeyspelare Position: back Moderklubb: Säsonger Matcher Mål Assist Poäng 1951/52 – – – – 1952/53 – – – – 1953/54 – – – – 1954/55 – – – –
Scraping: https://difhistoria.se/sune-andersson
	 Sune Anders Andersson Född: 21 april 1898 Fotbollsspelare Position: Moderklubb: 1 säsong. 3 matcher. 1 mål. 1927/28 3 1 Ishockeyspelare Position: forward Moderklubb: Säsonger Matcher Mål Assist Poäng 1921/22 – – – – 1922/23 – – – – 1923/24 – – – – 1924/25 – – – – 1925/26 – – – – 1926/27 – – – – 1927/28 – – – – 1928/29 – – – –
Scraping: https://difhistoria.se/tommy-andersson
	 John Tommy Kenneth Andersson Född: 24 september 1952 Fotbollsspelare Position: försvarare. Moderklubb: Trollhättans IF 1 säsong. 2 matcher. 0 mål. 1972 2 0
Scraping: https://difhistoria.se/tore-andersson
	 Tore Axel Alexander Andersson Född: 9 januari 1929 Ishockeyspelare Position: back Moderklubb: Säsonger Matcher Mål Assist Poäng 1949/50 – – – –
Scraping: https://difhistoria.se/ake-andersson
	 Åke Ragnar Andersson Född: 18 augusti 1906 Fotbollsspelare Position: Moderklubb: 1 säsong. 8 matcher. 2 mål. 1927/1928 8 2
Scraping: https://difhistoria.se/folke-andersson-arsjo
	 Folke Anders son-Arsjö Född: 19 februari 1903 Ishockeyspelare Position: forward Moderklubb: Säsonger Matcher Mål Assist Poäng 1922/23 – – – – 1923/24 – – – – 1924/25 – – – – 1925/26 – – – – 1926/27 – – – – 1927/28 – – – – 1928/29 – – – – 1929/30 – – – – 1930/31 – – – – 1931/32 – – – –
Scraping: https://difhistoria.se/knut-andersson-karsbrink
	 Knut Andersson-Karsbrink Född: 3 juli 1902 Ishockeyspelare Position: forward Moderklubb: Säsonger Matcher Mål Assist Poäng 1929/30 – – – –
Scraping: https://difhistoria.se/christer-andersson-mossberg-2
	 Christer Andersson-Mossberg Född: 15 februari 1939 Bandyspelare 6 säsonger. 1961 1962 1963 1964 1965 1966
Scraping: https://difhistoria.se/ivar-andre
	 Ivar Gustaf Harry André Född: 16 februari 1905 Fotbollsspelare Moderklubb: 1 säsong. 1 match. 1 mål. 1927/28 1 0
Scraping: https://difhistoria.se/anders-andren
	 Anders Andrén Född: 11 juli 1945 Ishockeyspelare Position: forward Moderklubb: Säsonger Matcher Mål Assist Poäng 1962/63 – 1 – – 1963/64 – 0 0 0 1964/65 10 – – – 1967/68 9 3 0 3 1968/69 17 6 4 10 1969/70 16 1 4 5 1970/71 7 1 0 1
Scraping: https://difhistoria.se/rune-andren
	 Nils Rune Andrén Född: 3 april 1950 Ishockeyspelare Position: forward Moderklubb: Säsonger Matcher Mål Assist Poäng 1968/69 – – – – 1969/70 – – – – 1970/71 – – – –
Scraping: https://difhistoria.se/vytautas-andriuskevicius
	 Vytautas Andriuskevicius Född: 8 oktober 1990 Fotbollsspelare Position: försvarare Moderklubb: FBK Kaunas 2 säsonger. 31 matcher. 0 mål. 2013 16 0 2014 15 0
Scraping: https://difhistoria.se/niklas-anger
	 Claes Niklas Folke Anger Född: 14 juli 1977 Ishockeyspelare Position: forward Moderklubb: Djurgårdens IF Säsonger Matcher Mål Assist Poäng 1968/69 – – – – 1969/70 – – – – 1970/71 – – – –
Scraping: https://difhistoria.se/goran-aral
	 Göran Timur Aral Född: 3 juli 1953 Fotbollsspelare Position: försvarare Moderklubb: Djurgårdens IF 1 säsong. 1 match. 0 mål. 1975 1 0
Scraping: https://difhistoria.se/kari-arnason
	 Kari Arnason Född: 13 oktober 1982 Fotbollsspelare Position: mittfältare Moderklubb: Vikingur Reykjavik (Island) 2 säsonger. 35 matcher.0 mål. 2005 21 0 SM-guld. Cupguld. 2006 14 0
Scraping: https://difhistoria.se/johan-arneng
	 Bo Johan Peter Arneng Född: 14 juni 1979 Fotbollsspelare Position: mittfältare Moderklubb: IK Oddevold 5 säsonger. 113 matcher. 9 mål. 2003 23 2 SM-guld. 2004 25 3 Cupguld. 2005 24 3 SM-guld. Cupguld. 2006 19 0 2007 22 1
Scraping: https://difhistoria.se/lars-laban-arnesson
	 Lars Arne Emanuel Arnesson Född: 20 februari 1936 Fotbollsspelare Position: back Moderklubb: Sandvikens IF 5 säsonger. 93 matcher. 1 mål. 1960 14 1 1961 17 0 1962 22 0 1963 17 0 1964 23 0 SM-guld. Bandyspelare 5 säsonger. 1961 1962 1963 1964 1965
Scraping: https://difhistoria.se/linus-arnesson
	 Linus Ola Arnesson Född: 21 september 1994 Ishockeyspelare Position: back Längd: 187 cm Nummer: 8 Skjuter: vänster Moderklubb: Hanvikens SK Säsonger Matcher Mål Assist Poäng 2011/12 3 0 0 0 2012/13 31 0 1 1 2013/14 44 1 5 6 2014/15 41 0 5 5 2021/22 43 2 2 4 2022/23 43 2 9 11
Scraping: https://difhistoria.se/jan-aronsson
	 Karl Gustaf Jan Aronsson Född: 28 november 1931 Fotbollsspelare Position: högerytter Moderklubb: Degerfors IF 1 säsong. 9 matcher. 2 mål. 1959 9 2
Scraping: https://difhistoria.se/mats-aronsson
	 Mats Olof Aronsson Född 16 augusti 1951 Fotbollsspelare Position: anfallare Moderklubb: Landskrona BoIS 2 säsonger. 33 matcher. 7 mål. 1981 19 2 1982 14 5
Scraping: https://difhistoria.se/ronnie-aronsson
	 Per Håkan Ronnie Aronsson Född: 14 juni 1961 Fotbollsspelare Position: anfallare Moderklubb: Djurgårdens IF 1 säsong. 5 matcher. 1 mål. 1981 5 1
Scraping: https://difhistoria.se/christer-andersson-mossberg
	 Folke Gustav Walter Arsjö Född: 19 februari 1903 Bandyspelare 2 säsonger. 1930 1931
Scraping: https://difhistoria.se/arne-arvidsson
	 Sven Arne Arvidsson Född: 19 januari 1929 Fotbollsspelare Position: målvakt Moderklubb: Långhyttans AIK 13 säsonger. 241 matcher. 0 mål. 1952/53 2 0 1953/54 22 0 1954/55 21 0 SM-guld. 1955/56 21 0 1956/57 20 0 1957/58 25 0 1959 22 0 SM-guld. 1960 22 0 1961 22 0 1962 21 0 1963 21 0 1964 22 0 SM-guld. 1965 20 0 Bandyspelare Position: målvakt 6 säsonger. 1961 1962 1963 1964 1965 1966
Scraping: https://difhistoria.se/jesper-arvidsson
	 John Jesper Arvidsson Född: 1 januari 1985 Fotbollsspelare Position: försvarare Moderklubb: Götene IF 3 säsonger. 61 matcher. 5 mål. 2013 15 0 2014 20 1 2015 26 4
Scraping: https://difhistoria.se/wilhelm-arwe
	 Karl Wilhelm Konrad Arwe Född: 28 januari 1898 SM guld: 1926 (ishockey) EM-guld: 1921 (ishockey) Stor grabb #6 ishockey Bandyspelare 2 säsonger 1930 1931 Ishockeyspelare Position: forward Moderklubb: Djurgårdens IF Säsonger Matcher Mål Assist Poäng 1921/22 – – – – 1922/23 – – – – 1923/24 – – – – 1924/25 – – – – 1925/26 – – – – 1926/27 – – – – 1927/28 – – – – 1928/29 – – – – 1929/30 – – – – 1930/31 – – – –
Scraping: https://difhistoria.se/joel-asoro
	 Joel Joshghene Asoro Född: 27 april 1999 Fotbollsspelare Position: anfallare Längd: 175 cm Nummer: 10 Moderklubb: IFK Haninge 2021 26 3 2022 2023
Scraping: https://difhistoria.se/ted-attersand
	 James Ted Attersand Född: 6 april 1952 Ishockeyspelare Position: back Moderklubb: Djurgårdens IF Säsonger Matcher Mål Assist Poäng 1969/70 – – – –
Scraping: https://difhistoria.se/jonathan-augustinsson
	 Hans Oskar Jonathan Augustinsson Född: 30 mars 1996 Fotbollsspelare Position: vänsterback Nummer: 15 Moderklubb: IF Brommapojkarna 3 säsonger. 50 matcher. 1 mål. 2017 8 0 2018 26 1 2019 16 0
Scraping: https://difhistoria.se/alf-axberg
	 Alf Gustaf Axberg Född: 4 april 1914 Ishockeyspelare Position: forward Moderklubb: Djurgårdens IF Säsonger Matcher Mål Assist Poäng 1930/31 – – – – 1931/32 – – – – 1932/33 – – – – 1933/34 – – – –
Scraping: https://difhistoria.se/yosif-ayuba
	 Yosif Ayuba Född: 30 november 1990 Fotbollsspelare Position: Moderklubb: 2 säsonger. 15 matcher. 1 mål. 2009 11 1 2010 4 0
Scraping: https://difhistoria.se/ibrahim-ba
	 Ibrahim Ba Född: 12 november 1973 Fotbollsspelare Position: anfallare Moderklubb: Çaykur Rizespor K (Turkiet) 1 säsong. 14 matcher. 1 mål. 2005 14 1 SM-guld. Cupguld.
Scraping: https://difhistoria.se/tomas-backman
	 Tomas Olof Edvard Backman Född: 16 juni 1980 Fotbollsspelare Position: försvarare/mittfältare Moderklubb: Friska Viljor FC 1 säsong. 11 matcher. 1 mål. 2004 11 1
Scraping: https://difhistoria.se/aliou-badji
	 Aliou Badji Född: 10 oktober 1997 Fotbollsspelare Position: anfallare Nummer: 20 Moderklubb: Casa Sports (senegal) 2 säsonger. 48 matcher. 11 mål. 2017 20 3 2018 28 8
Scraping: https://difhistoria.se/anna-bagge
	 Anna Karin Bagge Född: 30 januari 1973 Fotbollsspelare Position: back Nummer: Moderklubb: BP 1991 1992 1993 1994 1995 1996
Scraping: https://difhistoria.se/carlos-banda

In [17]:
# max 255
df["description_new"] = df["infobox"].str.slice(0,250)  
df["infobox_clean"] = (
    df["infobox"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()  
    )
df["description_new2"] = df["infobox_clean"].str.slice(0,250)

In [14]:
df.head()

,entry_id,catalog,external_id,external_url,name,description,entry_type,mnm_user_id,q,matched_on,matched_by_username,auxiliary_data,born,died,dates_in_wikidata,lat,lon,multi_match_candidates,infobox,description_new
0,225596324,7278,marja-aaltonen,https://difhistoria.se/marja-aaltonen,Marja Aaltonen,,Q5,6575119,Q24827502,20251217144436,Sabelöga,None,None,None,None,None,None,None,Marja Aaltonen Född: 13 maj 1964 Fotbollsspela...,Marja Aaltonen Född: 13 maj 1964 Fotbollsspela...
1,225596325,7278,alexander-abrahamsson,https://difhistoria.se/alexander-abrahamsson,Alexander Abrahamsson,,Q5,6575119,Q106475418,20251217144438,Sabelöga,None,None,None,None,None,None,None,Nils Oscar Alexander Abrahamsson Född: 7 augus...,Nils Oscar Alexander Abrahamsson Född: 7 augus...
2,225596326,7278,albion-ademi,https://difhistoria.se/albion-ademi,Albion Ademi,,Q5,6575119,Q26869094,20251217144445,Sabelöga,None,None,None,None,None,None,None,Albion Ademi Född: 19 februari 1999 Fotbollssp...,Albion Ademi Född: 19 februari 1999 Fotbollssp...
3,225596327,7278,gale-agbossoumonde,https://difhistoria.se/gale-agbossoumonde,Gale Agbossoumonde,,Q5,6575119,Q1491788,20251217144537,Sabelöga,None,None,None,None,None,None,None,Gale Agbossoumonde Född: 17 november 1991 Fotb...,Gale Agbossoumonde Född: 17 november 1991 Fotb...
4,225596328,7278,bengt-agfemalm,https://difhistoria.se/bengt-agfemalm,Bengt Agfemalm,,Q5,26041,Q138545451,20260303082020,Jssfrk,None,None,None,None,None,None,None,Bengt Frans Agfemalm Född: 24 augusti 1930 Cur...,Bengt Frans Agfemalm Född: 24 augusti 1930 Cur...

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1105 entries, 0 to 1104
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   entry_id                1105 non-null   object
 1   catalog                 1105 non-null   object
 2   external_id             1105 non-null   object
 3   external_url            1105 non-null   object
 4   name                    1105 non-null   object
 5   description             1105 non-null   object
 6   entry_type              1105 non-null   object
 7   mnm_user_id             712 non-null    object
 8   q                       712 non-null    object
 9   matched_on              712 non-null    object
 10  matched_by_username     712 non-null    object
 11  auxiliary_data          0 non-null      object
 12  born                    0 non-null      object
 13  died                    0 non-null      object
 14  dates_in_wikidata       0 non-null      object
 15  lat                     0 non-null      object
 16  lon                     0 non-null      object
 17  multi_match_candidates  20 non-null     object
 18  infobox                 1104 non-null   object
 19  description_new         1104 non-null   object
 20  infobox_clean           1104 non-null   object
 21  description_new2        1104 non-null   object
dtypes: object(22)
memory usage: 190.1+ KB

In [20]:
df["description_new2"]

0       Marja Aaltonen Född: 13 maj 1964 Fotbollsspela...
1       Nils Oscar Alexander Abrahamsson Född: 7 augus...
2       Albion Ademi Född: 19 februari 1999 Fotbollssp...
3       Gale Agbossoumonde Född: 17 november 1991 Fotb...
4       Bengt Frans Agfemalm Född: 24 augusti 1930 Cur...
                              ...
1100    Hans Östergren Född: x månad 19xx. Curlingspel...
1101    Lars Östergren Född: x månad 19xx Curlingspela...
1102    Irja Monika Österholm Född: 26 november 1959 F...
1103    Noah Andreas Östlund Född: 11 mars 2004 Ishock...
1104    Bo Thomas Östlund Född: 9 september 1965 Ishoc...
Name: description_new2, Length: 1105, dtype: object

In [25]:
out = df[["external_id","name","description_new2"]].copy()

out = out.rename(columns={
    "external_id":"id",
    "description_new2":"desc"
})

out["desc"] = out["desc"].str.slice(0,150)

out = out[out["desc"].notna()]
csv_outfile="mnm_diffhistory_update_20220306.csv"
out.to_csv(csv_outfile, index=False)

print(csv_outfile)

mnm_diffhistory_update_20220306.csv

In [26]:
out.head()

,id,name,desc
0,marja-aaltonen,Marja Aaltonen,Marja Aaltonen Född: 13 maj 1964 Fotbollsspela...
1,alexander-abrahamsson,Alexander Abrahamsson,Nils Oscar Alexander Abrahamsson Född: 7 augus...
2,albion-ademi,Albion Ademi,Albion Ademi Född: 19 februari 1999 Fotbollssp...
3,gale-agbossoumonde,Gale Agbossoumonde,Gale Agbossoumonde Född: 17 november 1991 Fotb...
4,bengt-agfemalm,Bengt Agfemalm,Bengt Frans Agfemalm Född: 24 augusti 1930 Cur...

In [23]:
# End timer
end_time = datetime.now()
duration = end_time - start_time

print("\n--- Execution Summary ---")
print(f"End time:      {end_time:%Y-%m-%d %H:%M:%S}")
print(f"Duration:      {duration}")
print(f"Total seconds: {duration.total_seconds():.2f}")
print(f"Python ver:    {sys.version.split()[0]}")
print(f"Platform:      {platform.system()} {platform.release()}")
print(f"Process ID:    {os.getpid()}")

--- Execution Summary ---
End time:      2026-03-06 11:05:34
Duration:      11:07:25.661561
Total seconds: 40045.66
Python ver:    3.12.2
Platform:      Darwin 25.3.0
Process ID:    96257